// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAapZuqanVoVUVE2PxxcNhA8CVNrpFAJfE',
    appId: '1:137591950253:web:17e0471d9612283325ef24',
    messagingSenderId: '137591950253',
    projectId: 'phoneauth-7ade4',
    authDomain: 'phoneauth-7ade4.firebaseapp.com',
    storageBucket: 'phoneauth-7ade4.appspot.com',
    measurementId: 'G-YY1RJYQB9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-TJLATcj_mqqURilGWnxeICHAmXZ2Sqo',
    appId: '1:137591950253:android:c5e411455004ad6a25ef24',
    messagingSenderId: '137591950253',
    projectId: 'phoneauth-7ade4',
    storageBucket: 'phoneauth-7ade4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXLn0vk1aq9D1CtgIMOWnLjfZxQoNTM1A',
    appId: '1:137591950253:ios:301a3972e602f33b25ef24',
    messagingSenderId: '137591950253',
    projectId: 'phoneauth-7ade4',
    storageBucket: 'phoneauth-7ade4.appspot.com',
    iosBundleId: 'com.example.collegeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXLn0vk1aq9D1CtgIMOWnLjfZxQoNTM1A',
    appId: '1:137591950253:ios:301a3972e602f33b25ef24',
    messagingSenderId: '137591950253',
    projectId: 'phoneauth-7ade4',
    storageBucket: 'phoneauth-7ade4.appspot.com',
    iosBundleId: 'com.example.collegeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAapZuqanVoVUVE2PxxcNhA8CVNrpFAJfE',
    appId: '1:137591950253:web:3e6aa7d6ac35bea025ef24',
    messagingSenderId: '137591950253',
    projectId: 'phoneauth-7ade4',
    authDomain: 'phoneauth-7ade4.firebaseapp.com',
    storageBucket: 'phoneauth-7ade4.appspot.com',
    measurementId: 'G-ZJNQP7P8R7',
  );
}
